[routes]
main = /
s_video = /pretty-petite-vr-pmv/
models = /pornstars/?sort=latest
s_model = /pornstars/samy-sun/
categories = /categories/
s_category = /tag/anal/
s_studio = /studio/vrbangers/
dreams = /camgirls/
s_dream = /camgirls/model-vrporn/
;all = /all/
;login = /login